using ECommerce.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ECommerce.Clases
{
    public class InstallHelper : IDisposable
    {
        private static ECommerceContext db = new ECommerceContext();

        public static void InitialConfiguration()
        {
            CrearCiudadesDeptos();
            insEmpresa();
            insReceta();
        }

        public static void CrearUnidades()
        {
            var consulta = db.Unidades.Count();
            if (consulta < 1)
            {
                insUnidad("Bolsas", 1);
                insUnidad("Buggys", 1);
                insUnidad("Bultos", 1);
                insUnidad("Cajas", 1);
                insUnidad("Cientos", 1);
                insUnidad("Conjuntos", 1);
                insUnidad("Decenas", 1);
                insUnidad("Docenas", 1);
                insUnidad("Frascos", 1);
                insUnidad("Galons", 1);
                insUnidad("Gramos", 1);
                insUnidad("Gruesas", 1);
                insUnidad("Juegos", 1);
                insUnidad("Kilogramos", 1);
                insUnidad("Libras", 1);
                insUnidad("Litros", 1);
                insUnidad("Madejas", 1);
                insUnidad("Metros", 1);
                insUnidad("Metro Cubicos", 1);
                insUnidad("Mililitros", 1);
                insUnidad("MIllares", 1);
                insUnidad("Paquetes", 1);
                insUnidad("Pares", 1);
                insUnidad("Rollos", 1);
                insUnidad("Toneladas", 1);
                insUnidad("Tubos", 1);
                insUnidad("Unidades", 1);
            }
        }

        public static void CrearCiudadesDeptos()
        {
            var consulta = db.Departamentos.Count();
            if (consulta < 1)
            {
                insDepto(1, "Amazonas");
                insDepto(2, "Antioquia");
                insDepto(3, "Arauca");
                insDepto(4, "Atlántico");
                insDepto(5, "Bolívar");
                insDepto(6, "Boyacá");
                insDepto(7, "Caldas");
                insDepto(8, "Caquetá");
                insDepto(9, "Casanare");
                insDepto(10, "Cauca");
                insDepto(11, "Cesar");
                insDepto(12, "Chocó");
                insDepto(13, "Córdoba");
                insDepto(14, "Cundinamarca");
                insDepto(15, "Güainia");
                insDepto(16, "Guaviare");
                insDepto(17, "Huila");
                insDepto(18, "La Guajira");
                insDepto(19, "Magdalena");
                insDepto(20, "Meta");
                insDepto(21, "Nariño");
                insDepto(22, "Norte de Santander");
                insDepto(23, "Putumayo");
                insDepto(24, "Quindio");
                insDepto(25, "Risaralda");
                insDepto(26, "San Andrés y Providencia");
                insDepto(27, "Santander");
                insDepto(28, "Sucre");
                insDepto(29, "Tolima");
                insDepto(30, "Valle del Cauca");
                insDepto(31, "Vaupés");
                insDepto(32, "Vichada");
                insCity(1, "Leticia", 1);
                insCity(2, "Puerto Nariño", 1);
                insCity(3, "Abejorral", 2);
                insCity(4, "Abriaquí", 2);
                insCity(5, "Alejandria", 2);
                insCity(6, "Amagá", 2);
                insCity(7, "Amalfi", 2);
                insCity(8, "Andes", 2);
                insCity(9, "Angelópolis", 2);
                insCity(10, "Angostura", 2);
                insCity(11, "Anorí", 2);
                insCity(12, "Anzá", 2);
                insCity(13, "Apartadó", 2);
                insCity(14, "Arboletes", 2);
                insCity(15, "Argelia", 2);
                insCity(16, "Armenia", 2);
                insCity(17, "Barbosa", 2);
                insCity(18, "Bello", 2);
                insCity(19, "Belmira", 2);
                insCity(20, "Betania", 2);
                insCity(21, "Betulia", 2);
                insCity(22, "Bolívar", 2);
                insCity(23, "Briceño", 2);
                insCity(24, "Burítica", 2);
                insCity(25, "Caicedo", 2);
                insCity(26, "Caldas", 2);
                insCity(27, "Campamento", 2);
                insCity(28, "Caracolí", 2);
                insCity(29, "Caramanta", 2);
                insCity(30, "Carepa", 2);
                insCity(31, "Carmen de Viboral", 2);
                insCity(32, "Carolina", 2);
                insCity(33, "Caucasia", 2);
                insCity(34, "Cañasgordas", 2);
                insCity(35, "Chigorodó", 2);
                insCity(36, "Cisneros", 2);
                insCity(37, "Cocorná", 2);
                insCity(38, "Concepción", 2);
                insCity(39, "Concordia", 2);
                insCity(40, "Copacabana", 2);
                insCity(41, "Cáceres", 2);
                insCity(42, "Dabeiba", 2);
                insCity(43, "Don Matías", 2);
                insCity(44, "Ebéjico", 2);
                insCity(45, "El Bagre", 2);
                insCity(46, "Entrerríos", 2);
                insCity(47, "Envigado", 2);
                insCity(48, "Fredonia", 2);
                insCity(49, "Frontino", 2);
                insCity(50, "Giraldo", 2);
                insCity(51, "Girardota", 2);
                insCity(52, "Granada", 2);
                insCity(53, "Guadalupe", 2);
                insCity(54, "Guarne", 2);
                insCity(55, "Guatapé", 2);
                insCity(56, "Gómez Plata", 2);
                insCity(57, "Heliconia", 2);
                insCity(58, "Hispania", 2);
                insCity(59, "Itagüí", 2);
                insCity(60, "Ituango", 2);
                insCity(61, "Jardín", 2);
                insCity(62, "Jericó", 2);
                insCity(63, "La Ceja", 2);
                insCity(64, "La Estrella", 2);
                insCity(65, "La Pintada", 2);
                insCity(66, "La Unión", 2);
                insCity(67, "Liborina", 2);
                insCity(68, "Maceo", 2);
                insCity(69, "Marinilla", 2);
                insCity(70, "Medellín", 2);
                insCity(71, "Montebello", 2);
                insCity(72, "Murindó", 2);
                insCity(73, "Mutatá", 2);
                insCity(74, "Nariño", 2);
                insCity(75, "Nechí", 2);
                insCity(76, "Necoclí", 2);
                insCity(77, "Olaya", 2);
                insCity(78, "Peque", 2);
                insCity(79, "Peñol", 2);
                insCity(80, "Pueblorrico", 2);
                insCity(81, "Puerto Berrío", 2);
                insCity(82, "Puerto Nare", 2);
                insCity(83, "Puerto Triunfo", 2);
                insCity(84, "Remedios", 2);
                insCity(85, "Retiro", 2);
                insCity(86, "Ríonegro", 2);
                insCity(87, "Sabanalarga", 2);
                insCity(88, "Sabaneta", 2);
                insCity(89, "Salgar", 2);
                insCity(90, "San Andrés de Cuerquía", 2);
                insCity(91, "San Carlos", 2);
                insCity(92, "San Francisco", 2);
                insCity(93, "San Jerónimo", 2);
                insCity(94, "San José de Montaña", 2);
                insCity(95, "San Juan de Urabá", 2);
                insCity(96, "San Luís", 2);
                insCity(97, "San Pedro", 2);
                insCity(98, "San Pedro de Urabá", 2);
                insCity(99, "San Rafael", 2);
                insCity(100, "San Roque", 2);
                insCity(101, "San Vicente", 2);
                insCity(102, "Santa Bárbara", 2);
                insCity(103, "Santa Fé de Antioquia", 2);
                insCity(104, "Santa Rosa de Osos", 2);
                insCity(105, "Santo Domingo", 2);
                insCity(106, "Santuario", 2);
                insCity(107, "Segovia", 2);
                insCity(108, "Sonsón", 2);
                insCity(109, "Sopetrán", 2);
                insCity(110, "Tarazá", 2);
                insCity(111, "Tarso", 2);
                insCity(112, "Titiribí", 2);
                insCity(113, "Toledo", 2);
                insCity(114, "Turbo", 2);
                insCity(115, "Támesis", 2);
                insCity(116, "Uramita", 2);
                insCity(117, "Urrao", 2);
                insCity(118, "Valdivia", 2);
                insCity(119, "Valparaiso", 2);
                insCity(120, "Vegachí", 2);
                insCity(121, "Venecia", 2);
                insCity(122, "Vigía del Fuerte", 2);
                insCity(123, "Yalí", 2);
                insCity(124, "Yarumal", 2);
                insCity(125, "Yolombó", 2);
                insCity(126, "Yondó  insCity(Casabe)", 2);
                insCity(127, "Zaragoza", 2);
                insCity(128, "Arauca", 3);
                insCity(129, "Arauquita", 3);
                insCity(130, "Cravo Norte", 3);
                insCity(131, "Fortúl", 3);
                insCity(132, "Puerto Rondón", 3);
                insCity(133, "Saravena", 3);
                insCity(134, "Tame", 3);
                insCity(135, "Baranoa", 4);
                insCity(136, "Barranquilla", 4);
                insCity(137, "Campo de la Cruz", 4);
                insCity(138, "Candelaria", 4);
                insCity(139, "Galapa", 4);
                insCity(140, "Juan de Acosta", 4);
                insCity(141, "Luruaco", 4);
                insCity(142, "Malambo", 4);
                insCity(143, "Manatí", 4);
                insCity(144, "Palmar de Varela", 4);
                insCity(145, "Piojo", 4);
                insCity(146, "Polonuevo", 4);
                insCity(147, "Ponedera", 4);
                insCity(148, "Puerto Colombia", 4);
                insCity(149, "Repelón", 4);
                insCity(150, "Sabanagrande", 4);
                insCity(151, "Sabanalarga", 4);
                insCity(152, "Santa Lucía", 4);
                insCity(153, "Santo Tomás", 4);
                insCity(154, "Soledad", 4);
                insCity(155, "Suan", 4);
                insCity(156, "Tubará", 4);
                insCity(157, "Usiacuri", 4);
                insCity(158, "Achí", 5);
                insCity(159, "Altos del Rosario", 5);
                insCity(160, "Arenal", 5);
                insCity(161, "Arjona", 5);
                insCity(162, "Arroyohondo", 5);
                insCity(163, "Barranco de Loba", 5);
                insCity(164, "Calamar", 5);
                insCity(165, "Cantagallo", 5);
                insCity(166, "Cartagena", 5);
                insCity(167, "Cicuco", 5);
                insCity(168, "Clemencia", 5);
                insCity(169, "Córdoba", 5);
                insCity(170, "El Carmen de Bolívar", 5);
                insCity(171, "El Guamo", 5);
                insCity(172, "El Peñon", 5);
                insCity(173, "Hatillo de Loba", 5);
                insCity(174, "Magangué", 5);
                insCity(175, "Mahates", 5);
                insCity(176, "Margarita", 5);
                insCity(177, "María la Baja", 5);
                insCity(178, "Mompós", 5);
                insCity(179, "Montecristo", 5);
                insCity(180, "Morales", 5);
                insCity(181, "Norosí", 5);
                insCity(182, "Pinillos", 5);
                insCity(183, "Regidor", 5);
                insCity(184, "Río Viejo", 5);
                insCity(185, "San Cristobal", 5);
                insCity(186, "San Estanislao", 5);
                insCity(187, "San Fernando", 5);
                insCity(188, "San Jacinto", 5);
                insCity(189, "San Jacinto del Cauca", 5);
                insCity(190, "San Juan de Nepomuceno", 5);
                insCity(191, "San Martín de Loba", 5);
                insCity(192, "San Pablo", 5);
                insCity(193, "Santa Catalina", 5);
                insCity(194, "Santa Rosa ", 5);
                insCity(195, "Santa Rosa del Sur", 5);
                insCity(196, "Simití", 5);
                insCity(197, "Soplaviento", 5);
                insCity(198, "Talaigua Nuevo", 5);
                insCity(199, "Tiquisio  insCity(Puerto Rico)", 5);
                insCity(200, "Turbaco", 5);
                insCity(201, "Turbaná", 5);
                insCity(202, "Villanueva", 5);
                insCity(203, "Zambrano", 5);
                insCity(204, "Almeida", 6);
                insCity(205, "Aquitania", 6);
                insCity(206, "Arcabuco", 6);
                insCity(207, "Belén", 6);
                insCity(208, "Berbeo", 6);
                insCity(209, "Beteitiva", 6);
                insCity(210, "Boavita", 6);
                insCity(211, "Boyacá", 6);
                insCity(212, "Briceño", 6);
                insCity(213, "Buenavista", 6);
                insCity(214, "Busbanza", 6);
                insCity(215, "Caldas", 6);
                insCity(216, "Campohermoso", 6);
                insCity(217, "Cerinza", 6);
                insCity(218, "Chinavita", 6);
                insCity(219, "Chiquinquirá", 6);
                insCity(220, "Chiscas", 6);
                insCity(221, "Chita", 6);
                insCity(222, "Chitaraque", 6);
                insCity(223, "Chivatá", 6);
                insCity(224, "Chíquiza", 6);
                insCity(225, "Chívor", 6);
                insCity(226, "Ciénaga", 6);
                insCity(227, "Coper", 6);
                insCity(228, "Corrales", 6);
                insCity(229, "Covarachía", 6);
                insCity(230, "Cubará", 6);
                insCity(231, "Cucaita", 6);
                insCity(232, "Cuitiva", 6);
                insCity(233, "Cómbita", 6);
                insCity(234, "Duitama", 6);
                insCity(235, "El Cocuy", 6);
                insCity(236, "El Espino", 6);
                insCity(237, "Firavitoba", 6);
                insCity(238, "Floresta", 6);
                insCity(239, "Gachantivá", 6);
                insCity(240, "Garagoa", 6);
                insCity(241, "Guacamayas", 6);
                insCity(242, "Guateque", 6);
                insCity(243, "Guayatá", 6);
                insCity(244, "Guicán", 6);
                insCity(245, "Gámeza", 6);
                insCity(246, "Izá", 6);
                insCity(247, "Jenesano", 6);
                insCity(248, "Jericó", 6);
                insCity(249, "La Capilla", 6);
                insCity(250, "La Uvita", 6);
                insCity(251, "La Victoria", 6);
                insCity(252, "Labranzagrande", 6);
                insCity(253, "Macanal", 6);
                insCity(254, "Maripí", 6);
                insCity(255, "Miraflores", 6);
                insCity(256, "Mongua", 6);
                insCity(257, "Monguí", 6);
                insCity(258, "Moniquirá", 6);
                insCity(259, "Motavita", 6);
                insCity(260, "Muzo", 6);
                insCity(261, "Nobsa", 6);
                insCity(262, "Nuevo Colón", 6);
                insCity(263, "Oicatá", 6);
                insCity(264, "Otanche", 6);
                insCity(265, "Pachavita", 6);
                insCity(266, "Paipa", 6);
                insCity(267, "Pajarito", 6);
                insCity(268, "Panqueba", 6);
                insCity(269, "Pauna", 6);
                insCity(270, "Paya", 6);
                insCity(271, "Paz de Río", 6);
                insCity(272, "Pesca", 6);
                insCity(273, "Pisva", 6);
                insCity(274, "Puerto Boyacá", 6);
                insCity(275, "Páez", 6);
                insCity(276, "Quipama", 6);
                insCity(277, "Ramiriquí", 6);
                insCity(278, "Rondón", 6);
                insCity(279, "Ráquira", 6);
                insCity(280, "Saboyá", 6);
                insCity(281, "Samacá", 6);
                insCity(282, "San Eduardo", 6);
                insCity(283, "San José de Pare", 6);
                insCity(284, "San Luís de Gaceno", 6);
                insCity(285, "San Mateo", 6);
                insCity(286, "San Miguel de Sema", 6);
                insCity(287, "San Pablo de Borbur", 6);
                insCity(288, "Santa María", 6);
                insCity(289, "Santa Rosa de Viterbo", 6);
                insCity(290, "Santa Sofía", 6);
                insCity(291, "Santana", 6);
                insCity(292, "Sativanorte", 6);
                insCity(293, "Sativasur", 6);
                insCity(294, "Siachoque", 6);
                insCity(295, "Soatá", 6);
                insCity(296, "Socha", 6);
                insCity(297, "Socotá", 6);
                insCity(298, "Sogamoso", 6);
                insCity(299, "Somondoco", 6);
                insCity(300, "Sora", 6);
                insCity(301, "Soracá", 6);
                insCity(302, "Sotaquirá", 6);
                insCity(303, "Susacón", 6);
                insCity(304, "Sutamarchán", 6);
                insCity(305, "Sutatenza", 6);
                insCity(306, "Sáchica", 6);
                insCity(307, "Tasco", 6);
                insCity(308, "Tenza", 6);
                insCity(309, "Tibaná", 6);
                insCity(310, "Tibasosa", 6);
                insCity(311, "Tinjacá", 6);
                insCity(312, "Tipacoque", 6);
                insCity(313, "Toca", 6);
                insCity(314, "Toguí", 6);
                insCity(315, "Topagá", 6);
                insCity(316, "Tota", 6);
                insCity(317, "Tunja", 6);
                insCity(318, "Tunungua", 6);
                insCity(319, "Turmequé", 6);
                insCity(320, "Tuta", 6);
                insCity(321, "Tutasá", 6);
                insCity(322, "Ventaquemada", 6);
                insCity(323, "Villa de Leiva", 6);
                insCity(324, "Viracachá", 6);
                insCity(325, "Zetaquirá", 6);
                insCity(326, "Úmbita", 6);
                insCity(327, "Aguadas", 7);
                insCity(328, "Anserma", 7);
                insCity(329, "Aranzazu", 7);
                insCity(330, "Belalcázar", 7);
                insCity(331, "Chinchiná", 7);
                insCity(332, "Filadelfia", 7);
                insCity(333, "La Dorada", 7);
                insCity(334, "La Merced", 7);
                insCity(335, "La Victoria", 7);
                insCity(336, "Manizales", 7);
                insCity(337, "Manzanares", 7);
                insCity(338, "Marmato", 7);
                insCity(339, "Marquetalia", 7);
                insCity(340, "Marulanda", 7);
                insCity(341, "Neira", 7);
                insCity(342, "Norcasia", 7);
                insCity(343, "Palestina", 7);
                insCity(344, "Pensilvania", 7);
                insCity(345, "Pácora", 7);
                insCity(346, "Risaralda", 7);
                insCity(347, "Río Sucio", 7);
                insCity(348, "Salamina", 7);
                insCity(349, "Samaná", 7);
                insCity(350, "San José", 7);
                insCity(351, "Supía", 7);
                insCity(352, "Villamaría", 7);
                insCity(353, "Viterbo", 7);
                insCity(354, "Albania", 8);
                insCity(355, "Belén de los Andaquíes", 8);
                insCity(356, "Cartagena del Chairá", 8);
                insCity(357, "Curillo", 8);
                insCity(358, "El Doncello", 8);
                insCity(359, "El Paujil", 8);
                insCity(360, "Florencia", 8);
                insCity(361, "La Montañita", 8);
                insCity(362, "Milán", 8);
                insCity(363, "Morelia", 8);
                insCity(364, "Puerto Rico", 8);
                insCity(365, "San José del Fragua", 8);
                insCity(366, "San Vicente del Caguán", 8);
                insCity(367, "Solano", 8);
                insCity(368, "Solita", 8);
                insCity(369, "Valparaiso", 8);
                insCity(370, "Aguazul", 9);
                insCity(371, "Chámeza", 9);
                insCity(372, "Hato Corozal", 9);
                insCity(373, "La Salina", 9);
                insCity(374, "Maní", 9);
                insCity(375, "Monterrey", 9);
                insCity(376, "Nunchía", 9);
                insCity(377, "Orocué", 9);
                insCity(378, "Paz de Ariporo", 9);
                insCity(379, "Pore", 9);
                insCity(380, "Recetor", 9);
                insCity(381, "Sabanalarga", 9);
                insCity(382, "San Luís de Palenque", 9);
                insCity(383, "Sácama", 9);
                insCity(384, "Tauramena", 9);
                insCity(385, "Trinidad", 9);
                insCity(386, "Támara", 9);
                insCity(387, "Villanueva", 9);
                insCity(388, "Yopal", 9);
                insCity(389, "Almaguer", 10);
                insCity(390, "Argelia", 10);
                insCity(391, "Balboa", 10);
                insCity(392, "Bolívar", 10);
                insCity(393, "Buenos Aires", 10);
                insCity(394, "Cajibío", 10);
                insCity(395, "Caldono", 10);
                insCity(396, "Caloto", 10);
                insCity(397, "Corinto", 10);
                insCity(398, "El Tambo", 10);
                insCity(399, "Florencia", 10);
                insCity(400, "Guachené", 10);
                insCity(401, "Guapí", 10);
                insCity(402, "Inzá", 10);
                insCity(403, "Jambaló", 10);
                insCity(404, "La Sierra", 10);
                insCity(405, "La Vega", 10);
                insCity(406, "López  insCity(Micay)", 10);
                insCity(407, "Mercaderes", 10);
                insCity(408, "Miranda", 10);
                insCity(409, "Morales", 10);
                insCity(410, "Padilla", 10);
                insCity(411, "Patía  insCity(El Bordo)", 10);
                insCity(412, "Piamonte", 10);
                insCity(413, "Piendamó", 10);
                insCity(414, "Popayán", 10);
                insCity(415, "Puerto Tejada", 10);
                insCity(416, "Puracé  insCity(Coconuco)", 10);
                insCity(417, "Páez  insCity(Belalcazar)", 10);
                insCity(418, "Rosas", 10);
                insCity(419, "San Sebastián", 10);
                insCity(420, "Santa Rosa", 10);
                insCity(421, "Santander de Quilichao", 10);
                insCity(422, "Silvia", 10);
                insCity(423, "Sotara  insCity(Paispamba)", 10);
                insCity(424, "Sucre", 10);
                insCity(425, "Suárez", 10);
                insCity(426, "Timbiquí", 10);
                insCity(427, "Timbío", 10);
                insCity(428, "Toribío", 10);
                insCity(429, "Totoró", 10);
                insCity(430, "Villa Rica", 10);
                insCity(431, "Aguachica", 11);
                insCity(432, "Agustín Codazzi", 11);
                insCity(433, "Astrea", 11);
                insCity(434, "Becerríl", 11);
                insCity(435, "Bosconia", 11);
                insCity(436, "Chimichagua", 11);
                insCity(437, "Chiriguaná", 11);
                insCity(438, "Curumaní", 11);
                insCity(439, "El Copey", 11);
                insCity(440, "El Paso", 11);
                insCity(441, "Gamarra", 11);
                insCity(442, "Gonzalez", 11);
                insCity(443, "La Gloria", 11);
                insCity(444, "La Jagua de Ibirico", 11);
                insCity(445, "La Paz  insCity(Robles)", 11);
                insCity(446, "Manaure Balcón del Cesar", 11);
                insCity(447, "Pailitas", 11);
                insCity(448, "Pelaya", 11);
                insCity(449, "Pueblo Bello", 11);
                insCity(450, "Río de oro", 11);
                insCity(451, "San Alberto", 11);
                insCity(452, "San Diego", 11);
                insCity(453, "San Martín", 11);
                insCity(454, "Tamalameque", 11);
                insCity(455, "Valledupar", 11);
                insCity(456, "Acandí", 12);
                insCity(457, "Alto Baudó  insCity(Pie de Pato)", 12);
                insCity(458, "Atrato  insCity(Yuto)", 12);
                insCity(459, "Bagadó", 12);
                insCity(460, "Bahía Solano  insCity(Mútis)", 12);
                insCity(461, "Bajo Baudó  insCity(Pizarro)", 12);
                insCity(462, "Belén de Bajirá", 12);
                insCity(463, "Bojayá  insCity(Bellavista)", 12);
                insCity(464, "Cantón de San Pablo", 12);
                insCity(465, "Carmen del Darién  insCity(CURBARADÓ)", 12);
                insCity(466, "Condoto", 12);
                insCity(467, "Cértegui", 12);
                insCity(468, "El Carmen de Atrato", 12);
                insCity(469, "Istmina", 12);
                insCity(470, "Juradó", 12);
                insCity(471, "Lloró", 12);
                insCity(472, "Medio Atrato", 12);
                insCity(473, "Medio Baudó", 12);
                insCity(474, "Medio San Juan  insCity(ANDAGOYA)", 12);
                insCity(475, "Novita", 12);
                insCity(476, "Nuquí", 12);
                insCity(477, "Quibdó", 12);
                insCity(478, "Río Iró", 12);
                insCity(479, "Río Quito", 12);
                insCity(480, "Ríosucio", 12);
                insCity(481, "San José del Palmar", 12);
                insCity(482, "Santa Genoveva de Docorodó", 12);
                insCity(483, "Sipí", 12);
                insCity(484, "Tadó", 12);
                insCity(485, "Unguía", 12);
                insCity(486, "Unión Panamericana  insCity(ÁNIMAS)", 12);
                insCity(487, "Ayapel", 13);
                insCity(488, "Buenavista", 13);
                insCity(489, "Canalete", 13);
                insCity(490, "Cereté", 13);
                insCity(491, "Chimá", 13);
                insCity(492, "Chinú", 13);
                insCity(493, "Ciénaga de Oro", 13);
                insCity(494, "Cotorra", 13);
                insCity(495, "La Apartada y La Frontera", 13);
                insCity(496, "Lorica", 13);
                insCity(497, "Los Córdobas", 13);
                insCity(498, "Momil", 13);
                insCity(499, "Montelíbano", 13);
                insCity(500, "Monteria", 13);
                insCity(501, "Moñitos", 13);
                insCity(502, "Planeta Rica", 13);
                insCity(503, "Pueblo Nuevo", 13);
                insCity(504, "Puerto Escondido", 13);
                insCity(505, "Puerto Libertador", 13);
                insCity(506, "Purísima", 13);
                insCity(507, "Sahagún", 13);
                insCity(508, "San Andrés Sotavento", 13);
                insCity(509, "San Antero", 13);
                insCity(510, "San Bernardo del Viento", 13);
                insCity(511, "San Carlos", 13);
                insCity(512, "San José de Uré", 13);
                insCity(513, "San Pelayo", 13);
                insCity(514, "Tierralta", 13);
                insCity(515, "Tuchín", 13);
                insCity(516, "Valencia", 13);
                insCity(517, "Agua de Dios", 14);
                insCity(518, "Albán", 14);
                insCity(519, "Anapoima", 14);
                insCity(520, "Anolaima", 14);
                insCity(521, "Apulo", 14);
                insCity(522, "Arbeláez", 14);
                insCity(523, "Beltrán", 14);
                insCity(524, "Bituima", 14);
                insCity(525, "Bogotá D.C.", 14);
                insCity(526, "Bojacá", 14);
                insCity(527, "Cabrera", 14);
                insCity(528, "Cachipay", 14);
                insCity(529, "Cajicá", 14);
                insCity(530, "Caparrapí", 14);
                insCity(531, "Carmen de Carupa", 14);
                insCity(532, "Chaguaní", 14);
                insCity(533, "Chipaque", 14);
                insCity(534, "Choachí", 14);
                insCity(535, "Chocontá", 14);
                insCity(536, "Chía", 14);
                insCity(537, "Cogua", 14);
                insCity(538, "Cota", 14);
                insCity(539, "Cucunubá", 14);
                insCity(540, "Cáqueza", 14);
                insCity(541, "El Colegio", 14);
                insCity(542, "El Peñón", 14);
                insCity(543, "El Rosal", 14);
                insCity(544, "Facatativá", 14);
                insCity(545, "Fosca", 14);
                insCity(546, "Funza", 14);
                insCity(547, "Fusagasugá", 14);
                insCity(548, "Fómeque", 14);
                insCity(549, "Fúquene", 14);
                insCity(550, "Gachalá", 14);
                insCity(551, "Gachancipá", 14);
                insCity(552, "Gachetá", 14);
                insCity(553, "Gama", 14);
                insCity(554, "Girardot", 14);
                insCity(555, "Granada", 14);
                insCity(556, "Guachetá", 14);
                insCity(557, "Guaduas", 14);
                insCity(558, "Guasca", 14);
                insCity(559, "Guataquí", 14);
                insCity(560, "Guatavita", 14);
                insCity(561, "Guayabal de Siquima", 14);
                insCity(562, "Guayabetal", 14);
                insCity(563, "Gutiérrez", 14);
                insCity(564, "Jerusalén", 14);
                insCity(565, "Junín", 14);
                insCity(566, "La Calera", 14);
                insCity(567, "La Mesa", 14);
                insCity(568, "La Palma", 14);
                insCity(569, "La Peña", 14);
                insCity(570, "La Vega", 14);
                insCity(571, "Lenguazaque", 14);
                insCity(572, "Machetá", 14);
                insCity(573, "Madrid", 14);
                insCity(574, "Manta", 14);
                insCity(575, "Medina", 14);
                insCity(576, "Mosquera", 14);
                insCity(577, "Nariño", 14);
                insCity(578, "Nemocón", 14);
                insCity(579, "Nilo", 14);
                insCity(580, "Nimaima", 14);
                insCity(581, "Nocaima", 14);
                insCity(582, "Pacho", 14);
                insCity(583, "Paime", 14);
                insCity(584, "Pandi", 14);
                insCity(585, "Paratebueno", 14);
                insCity(586, "Pasca", 14);
                insCity(587, "Puerto Salgar", 14);
                insCity(588, "Pulí", 14);
                insCity(589, "Quebradanegra", 14);
                insCity(590, "Quetame", 14);
                insCity(591, "Quipile", 14);
                insCity(592, "Ricaurte", 14);
                insCity(593, "San Antonio de Tequendama", 14);
                insCity(594, "San Bernardo", 14);
                insCity(595, "San Cayetano", 14);
                insCity(596, "San Francisco", 14);
                insCity(597, "San Juan de Río Seco", 14);
                insCity(598, "Sasaima", 14);
                insCity(599, "Sesquilé", 14);
                insCity(600, "Sibaté", 14);
                insCity(601, "Silvania", 14);
                insCity(602, "Simijaca", 14);
                insCity(603, "Soacha", 14);
                insCity(604, "Sopó", 14);
                insCity(605, "Subachoque", 14);
                insCity(606, "Suesca", 14);
                insCity(607, "Supatá", 14);
                insCity(608, "Susa", 14);
                insCity(609, "Sutatausa", 14);
                insCity(610, "Tabio", 14);
                insCity(611, "Tausa", 14);
                insCity(612, "Tena", 14);
                insCity(613, "Tenjo", 14);
                insCity(614, "Tibacuy", 14);
                insCity(615, "Tibirita", 14);
                insCity(616, "Tocaima", 14);
                insCity(617, "Tocancipá", 14);
                insCity(618, "Topaipí", 14);
                insCity(619, "Ubalá", 14);
                insCity(620, "Ubaque", 14);
                insCity(621, "Ubaté", 14);
                insCity(622, "Une", 14);
                insCity(623, "Venecia  insCity(Ospina Pérez)", 14);
                insCity(624, "Vergara", 14);
                insCity(625, "Viani", 14);
                insCity(626, "Villagómez", 14);
                insCity(627, "Villapinzón", 14);
                insCity(628, "Villeta", 14);
                insCity(629, "Viotá", 14);
                insCity(630, "Yacopí", 14);
                insCity(631, "Zipacón", 14);
                insCity(632, "Zipaquirá", 14);
                insCity(633, "Útica", 14);
                insCity(634, "Inírida", 15);
                insCity(635, "Calamar", 16);
                insCity(636, "El Retorno", 16);
                insCity(637, "Miraflores", 16);
                insCity(638, "San José del Guaviare", 16);
                insCity(639, "Acevedo", 17);
                insCity(640, "Agrado", 17);
                insCity(641, "Aipe", 17);
                insCity(642, "Algeciras", 17);
                insCity(643, "Altamira", 17);
                insCity(644, "Baraya", 17);
                insCity(645, "Campoalegre", 17);
                insCity(646, "Colombia", 17);
                insCity(647, "Elías", 17);
                insCity(648, "Garzón", 17);
                insCity(649, "Gigante", 17);
                insCity(650, "Guadalupe", 17);
                insCity(651, "Hobo", 17);
                insCity(652, "Isnos", 17);
                insCity(653, "La Argentina", 17);
                insCity(654, "La Plata", 17);
                insCity(655, "Neiva", 17);
                insCity(656, "Nátaga", 17);
                insCity(657, "Oporapa", 17);
                insCity(658, "Paicol", 17);
                insCity(659, "Palermo", 17);
                insCity(660, "Palestina", 17);
                insCity(661, "Pital", 17);
                insCity(662, "Pitalito", 17);
                insCity(663, "Rivera", 17);
                insCity(664, "Saladoblanco", 17);
                insCity(665, "San Agustín", 17);
                insCity(666, "Santa María", 17);
                insCity(667, "Suaza", 17);
                insCity(668, "Tarqui", 17);
                insCity(669, "Tello", 17);
                insCity(670, "Teruel", 17);
                insCity(671, "Tesalia", 17);
                insCity(672, "Timaná", 17);
                insCity(673, "Villavieja", 17);
                insCity(674, "Yaguará", 17);
                insCity(675, "Íquira", 17);
                insCity(676, "Albania", 18);
                insCity(677, "Barrancas", 18);
                insCity(678, "Dibulla", 18);
                insCity(679, "Distracción", 18);
                insCity(680, "El Molino", 18);
                insCity(681, "Fonseca", 18);
                insCity(682, "Hatonuevo", 18);
                insCity(683, "La Jagua del Pilar", 18);
                insCity(684, "Maicao", 18);
                insCity(685, "Manaure", 18);
                insCity(686, "Riohacha", 18);
                insCity(687, "San Juan del Cesar", 18);
                insCity(688, "Uribia", 18);
                insCity(689, "Urumita", 18);
                insCity(690, "Villanueva", 18);
                insCity(691, "Algarrobo", 19);
                insCity(692, "Aracataca", 19);
                insCity(693, "Ariguaní  insCity(El Difícil)", 19);
                insCity(694, "Cerro San Antonio", 19);
                insCity(695, "Chivolo", 19);
                insCity(696, "Ciénaga", 19);
                insCity(697, "Concordia", 19);
                insCity(698, "El Banco", 19);
                insCity(699, "El Piñon", 19);
                insCity(700, "El Retén", 19);
                insCity(701, "Fundación", 19);
                insCity(702, "Guamal", 19);
                insCity(703, "Nueva Granada", 19);
                insCity(704, "Pedraza", 19);
                insCity(705, "Pijiño", 19);
                insCity(706, "Pivijay", 19);
                insCity(707, "Plato", 19);
                insCity(708, "Puebloviejo", 19);
                insCity(709, "Remolino", 19);
                insCity(710, "Sabanas de San Angel  insCity(SAN ANGEL)", 19);
                insCity(711, "Salamina", 19);
                insCity(712, "San Sebastián de Buenavista", 19);
                insCity(713, "San Zenón", 19);
                insCity(714, "Santa Ana", 19);
                insCity(715, "Santa Bárbara de Pinto", 19);
                insCity(716, "Santa Marta", 19);
                insCity(717, "Sitionuevo", 19);
                insCity(718, "Tenerife", 19);
                insCity(719, "Zapayán  insCity(PUNTA DE PIEDRAS)", 19);
                insCity(720, "Zona Bananera  insCity(PRADO - SEVILLA)", 19);
                insCity(721, "Acacías", 20);
                insCity(722, "Barranca de Upía", 20);
                insCity(723, "Cabuyaro", 20);
                insCity(724, "Castilla la Nueva", 20);
                insCity(725, "Cubarral", 20);
                insCity(726, "Cumaral", 20);
                insCity(727, "El Calvario", 20);
                insCity(728, "El Castillo", 20);
                insCity(729, "El Dorado", 20);
                insCity(730, "Fuente de Oro", 20);
                insCity(731, "Granada", 20);
                insCity(732, "Guamal", 20);
                insCity(733, "La Macarena", 20);
                insCity(734, "Lejanías", 20);
                insCity(735, "Mapiripan", 20);
                insCity(736, "Mesetas", 20);
                insCity(737, "Puerto Concordia", 20);
                insCity(738, "Puerto Gaitán", 20);
                insCity(739, "Puerto Lleras", 20);
                insCity(740, "Puerto López", 20);
                insCity(741, "Puerto Rico", 20);
                insCity(742, "Restrepo", 20);
                insCity(743, "San Carlos de Guaroa", 20);
                insCity(744, "San Juan de Arama", 20);
                insCity(745, "San Juanito", 20);
                insCity(746, "San Martín", 20);
                insCity(747, "Uribe", 20);
                insCity(748, "Villavicencio", 20);
                insCity(749, "Vista Hermosa", 20);
                insCity(750, "Albán  insCity(San José)", 21);
                insCity(751, "Aldana", 21);
                insCity(752, "Ancuya", 21);
                insCity(753, "Arboleda  insCity(Berruecos)", 21);
                insCity(754, "Barbacoas", 21);
                insCity(755, "Belén", 21);
                insCity(756, "Buesaco", 21);
                insCity(757, "Chachaguí", 21);
                insCity(758, "Colón  insCity(Génova)", 21);
                insCity(759, "Consaca", 21);
                insCity(760, "Contadero", 21);
                insCity(761, "Cuaspud  insCity(Carlosama)", 21);
                insCity(762, "Cumbal", 21);
                insCity(763, "Cumbitara", 21);
                insCity(764, "Córdoba", 21);
                insCity(765, "El Charco", 21);
                insCity(766, "El Peñol", 21);
                insCity(767, "El Rosario", 21);
                insCity(768, "El Tablón de Gómez", 21);
                insCity(769, "El Tambo", 21);
                insCity(770, "Francisco Pizarro", 21);
                insCity(771, "Funes", 21);
                insCity(772, "Guachavés", 21);
                insCity(773, "Guachucal", 21);
                insCity(774, "Guaitarilla", 21);
                insCity(775, "Gualmatán", 21);
                insCity(776, "Iles", 21);
                insCity(777, "Imúes", 21);
                insCity(778, "Ipiales", 21);
                insCity(779, "La Cruz", 21);
                insCity(780, "La Florida", 21);
                insCity(781, "La Llanada", 21);
                insCity(782, "La Tola", 21);
                insCity(783, "La Unión", 21);
                insCity(784, "Leiva", 21);
                insCity(785, "Linares", 21);
                insCity(786, "Magüi  insCity(Payán)", 21);
                insCity(787, "Mallama  insCity(Piedrancha)", 21);
                insCity(788, "Mosquera", 21);
                insCity(789, "Nariño", 21);
                insCity(790, "Olaya Herrera", 21);
                insCity(791, "Ospina", 21);
                insCity(792, "Policarpa", 21);
                insCity(793, "Potosí", 21);
                insCity(794, "Providencia", 21);
                insCity(795, "Puerres", 21);
                insCity(796, "Pupiales", 21);
                insCity(797, "Ricaurte", 21);
                insCity(798, "Roberto Payán  insCity(San José)", 21);
                insCity(799, "Samaniego", 21);
                insCity(800, "San Bernardo", 21);
                insCity(801, "Pasto", 21);
                insCity(802, "San Lorenzo", 21);
                insCity(803, "San Pablo", 21);
                insCity(804, "San Pedro de Cartago", 21);
                insCity(805, "Sandoná", 21);
                insCity(806, "Santa Bárbara  insCity(Iscuandé)", 21);
                insCity(807, "Sapuyes", 21);
                insCity(808, "Sotomayor  insCity(Los Andes)", 21);
                insCity(809, "Taminango", 21);
                insCity(810, "Tangua", 21);
                insCity(811, "Tumaco", 21);
                insCity(812, "Túquerres", 21);
                insCity(813, "Yacuanquer", 21);
                insCity(814, "Arboledas", 22);
                insCity(815, "Bochalema", 22);
                insCity(816, "Bucarasica", 22);
                insCity(817, "Chinácota", 22);
                insCity(818, "Chitagá", 22);
                insCity(819, "Convención", 22);
                insCity(820, "Cucutilla", 22);
                insCity(821, "Cáchira", 22);
                insCity(822, "Cácota", 22);
                insCity(823, "Cúcuta", 22);
                insCity(824, "Durania", 22);
                insCity(825, "El Carmen", 22);
                insCity(826, "El Tarra", 22);
                insCity(827, "El Zulia", 22);
                insCity(828, "Gramalote", 22);
                insCity(829, "Hacarí", 22);
                insCity(830, "Herrán", 22);
                insCity(831, "La Esperanza", 22);
                insCity(832, "La Playa", 22);
                insCity(833, "Labateca", 22);
                insCity(834, "Los Patios", 22);
                insCity(835, "Lourdes", 22);
                insCity(836, "Mutiscua", 22);
                insCity(837, "Ocaña", 22);
                insCity(838, "Pamplona", 22);
                insCity(839, "Pamplonita", 22);
                insCity(840, "Puerto Santander", 22);
                insCity(841, "Ragonvalia", 22);
                insCity(842, "Salazar", 22);
                insCity(843, "San Calixto", 22);
                insCity(844, "San Cayetano", 22);
                insCity(845, "Santiago", 22);
                insCity(846, "Sardinata", 22);
                insCity(847, "Silos", 22);
                insCity(848, "Teorama", 22);
                insCity(849, "Tibú", 22);
                insCity(850, "Toledo", 22);
                insCity(851, "Villa Caro", 22);
                insCity(852, "Villa del Rosario", 22);
                insCity(853, "Ábrego", 22);
                insCity(854, "Colón", 23);
                insCity(855, "Mocoa", 23);
                insCity(856, "Orito", 23);
                insCity(857, "Puerto Asís", 23);
                insCity(858, "Puerto Caicedo", 23);
                insCity(859, "Puerto Guzmán", 23);
                insCity(860, "Puerto Leguízamo", 23);
                insCity(861, "San Francisco", 23);
                insCity(862, "San Miguel", 23);
                insCity(863, "Santiago", 23);
                insCity(864, "Sibundoy", 23);
                insCity(865, "Valle del Guamuez", 23);
                insCity(866, "Villagarzón", 23);
                insCity(867, "Armenia", 24);
                insCity(868, "Buenavista", 24);
                insCity(869, "Calarcá", 24);
                insCity(870, "Circasia", 24);
                insCity(871, "Cordobá", 24);
                insCity(872, "Filandia", 24);
                insCity(873, "Génova", 24);
                insCity(874, "La Tebaida", 24);
                insCity(875, "Montenegro", 24);
                insCity(876, "Pijao", 24);
                insCity(877, "Quimbaya", 24);
                insCity(878, "Salento", 24);
                insCity(879, "Apía", 25);
                insCity(880, "Balboa", 25);
                insCity(881, "Belén de Umbría", 25);
                insCity(882, "Dos Quebradas", 25);
                insCity(883, "Guática", 25);
                insCity(884, "La Celia", 25);
                insCity(885, "La Virginia", 25);
                insCity(886, "Marsella", 25);
                insCity(887, "Mistrató", 25);
                insCity(888, "Pereira", 25);
                insCity(889, "Pueblo Rico", 25);
                insCity(890, "Quinchía", 25);
                insCity(891, "Santa Rosa de Cabal", 25);
                insCity(892, "Santuario", 25);
                insCity(893, "Providencia", 26);
                insCity(894, "Aguada", 27);
                insCity(895, "Albania", 27);
                insCity(896, "Aratoca", 27);
                insCity(897, "Barbosa", 27);
                insCity(898, "Barichara", 27);
                insCity(899, "Barrancabermeja", 27);
                insCity(900, "Betulia", 27);
                insCity(901, "Bolívar", 27);
                insCity(902, "Bucaramanga", 27);
                insCity(903, "Cabrera", 27);
                insCity(904, "California", 27);
                insCity(905, "Capitanejo", 27);
                insCity(906, "Carcasí", 27);
                insCity(907, "Cepita", 27);
                insCity(908, "Cerrito", 27);
                insCity(909, "Charalá", 27);
                insCity(910, "Charta", 27);
                insCity(911, "Chima", 27);
                insCity(912, "Chipatá", 27);
                insCity(913, "Cimitarra", 27);
                insCity(914, "Concepción", 27);
                insCity(915, "Confines", 27);
                insCity(916, "Contratación", 27);
                insCity(917, "Coromoro", 27);
                insCity(918, "Curití", 27);
                insCity(919, "El Carmen", 27);
                insCity(920, "El Guacamayo", 27);
                insCity(921, "El Peñon", 27);
                insCity(922, "El Playón", 27);
                insCity(923, "Encino", 27);
                insCity(924, "Enciso", 27);
                insCity(925, "Floridablanca", 27);
                insCity(926, "Florián", 27);
                insCity(927, "Galán", 27);
                insCity(928, "Girón", 27);
                insCity(929, "Guaca", 27);
                insCity(930, "Guadalupe", 27);
                insCity(931, "Guapota", 27);
                insCity(932, "Guavatá", 27);
                insCity(933, "Guepsa", 27);
                insCity(934, "Gámbita", 27);
                insCity(935, "Hato", 27);
                insCity(936, "Jesús María", 27);
                insCity(937, "Jordán", 27);
                insCity(938, "La Belleza", 27);
                insCity(939, "La Paz", 27);
                insCity(940, "Landázuri", 27);
                insCity(941, "Lebrija", 27);
                insCity(942, "Los Santos", 27);
                insCity(943, "Macaravita", 27);
                insCity(944, "Matanza", 27);
                insCity(945, "Mogotes", 27);
                insCity(946, "Molagavita", 27);
                insCity(947, "Málaga", 27);
                insCity(948, "Ocamonte", 27);
                insCity(949, "Oiba", 27);
                insCity(950, "Onzaga", 27);
                insCity(951, "Palmar", 27);
                insCity(952, "Palmas del Socorro", 27);
                insCity(953, "Pie de Cuesta", 27);
                insCity(954, "Pinchote", 27);
                insCity(955, "Puente Nacional", 27);
                insCity(956, "Puerto Parra", 27);
                insCity(957, "Puerto Wilches", 27);
                insCity(958, "Páramo", 27);
                insCity(959, "Rio Negro", 27);
                insCity(960, "Sabana de Torres", 27);
                insCity(961, "San Andrés", 27);
                insCity(962, "San Benito", 27);
                insCity(963, "San Gíl", 27);
                insCity(964, "San Joaquín", 27);
                insCity(965, "San José de Miranda", 27);
                insCity(966, "San Miguel", 27);
                insCity(967, "San Vicente del Chucurí", 27);
                insCity(968, "Santa Bárbara", 27);
                insCity(969, "Santa Helena del Opón", 27);
                insCity(970, "Simacota", 27);
                insCity(971, "Socorro", 27);
                insCity(972, "Suaita", 27);
                insCity(973, "Sucre", 27);
                insCity(974, "Suratá", 27);
                insCity(975, "Tona", 27);
                insCity(976, "Valle de San José", 27);
                insCity(977, "Vetas", 27);
                insCity(978, "Villanueva", 27);
                insCity(979, "Vélez", 27);
                insCity(980, "Zapatoca", 27);
                insCity(981, "Buenavista", 28);
                insCity(982, "Caimito", 28);
                insCity(983, "Chalán", 28);
                insCity(984, "Colosó  insCity(Ricaurte)", 28);
                insCity(985, "Corozal", 28);
                insCity(986, "Coveñas", 28);
                insCity(987, "El Roble", 28);
                insCity(988, "Galeras  insCity(Nueva Granada)", 28);
                insCity(989, "Guaranda", 28);
                insCity(990, "La Unión", 28);
                insCity(991, "Los Palmitos", 28);
                insCity(992, "Majagual", 28);
                insCity(993, "Morroa", 28);
                insCity(994, "Ovejas", 28);
                insCity(995, "Palmito", 28);
                insCity(996, "Sampués", 28);
                insCity(997, "San Benito Abad", 28);
                insCity(998, "San Juan de Betulia", 28);
                insCity(999, "San Marcos", 28);
                insCity(1000, "San Onofre", 28);
                insCity(1001, "San Pedro", 28);
                insCity(1002, "Sincelejo", 28);
                insCity(1003, "Sincé", 28);
                insCity(1004, "Sucre", 28);
                insCity(1005, "Tolú", 28);
                insCity(1006, "Tolú Viejo", 28);
                insCity(1007, "Alpujarra", 29);
                insCity(1008, "Alvarado", 29);
                insCity(1009, "Ambalema", 29);
                insCity(1010, "Anzoátegui", 29);
                insCity(1011, "Armero  insCity(Guayabal)", 29);
                insCity(1012, "Ataco", 29);
                insCity(1013, "Cajamarca", 29);
                insCity(1014, "Carmen de Apicalá", 29);
                insCity(1015, "Casabianca", 29);
                insCity(1016, "Chaparral", 29);
                insCity(1017, "Coello", 29);
                insCity(1018, "Coyaima", 29);
                insCity(1019, "Cunday", 29);
                insCity(1020, "Dolores", 29);
                insCity(1021, "Espinal", 29);
                insCity(1022, "Falan", 29);
                insCity(1023, "Flandes", 29);
                insCity(1024, "Fresno", 29);
                insCity(1025, "Guamo", 29);
                insCity(1026, "Herveo", 29);
                insCity(1027, "Honda", 29);
                insCity(1028, "Ibagué", 29);
                insCity(1029, "Icononzo", 29);
                insCity(1030, "Lérida", 29);
                insCity(1031, "Líbano", 29);
                insCity(1032, "Mariquita", 29);
                insCity(1033, "Melgar", 29);
                insCity(1034, "Murillo", 29);
                insCity(1035, "Natagaima", 29);
                insCity(1036, "Ortega", 29);
                insCity(1037, "Palocabildo", 29);
                insCity(1038, "Piedras", 29);
                insCity(1039, "Planadas", 29);
                insCity(1040, "Prado", 29);
                insCity(1041, "Purificación", 29);
                insCity(1042, "Rioblanco", 29);
                insCity(1043, "Roncesvalles", 29);
                insCity(1044, "Rovira", 29);
                insCity(1045, "Saldaña", 29);
                insCity(1046, "San Antonio", 29);
                insCity(1047, "San Luis", 29);
                insCity(1048, "Santa Isabel", 29);
                insCity(1049, "Suárez", 29);
                insCity(1050, "Valle de San Juan", 29);
                insCity(1051, "Venadillo", 29);
                insCity(1052, "Villahermosa", 29);
                insCity(1053, "Villarrica", 29);
                insCity(1054, "Alcalá", 30);
                insCity(1055, "Andalucía", 30);
                insCity(1056, "Ansermanuevo", 30);
                insCity(1057, "Argelia", 30);
                insCity(1058, "Bolívar", 30);
                insCity(1059, "Buenaventura", 30);
                insCity(1060, "Buga", 30);
                insCity(1061, "Bugalagrande", 30);
                insCity(1062, "Caicedonia", 30);
                insCity(1063, "Calima  insCity(Darién)", 30);
                insCity(1064, "Calí", 30);
                insCity(1065, "Candelaria", 30);
                insCity(1066, "Cartago", 30);
                insCity(1067, "Dagua", 30);
                insCity(1068, "El Cairo", 30);
                insCity(1069, "El Cerrito", 30);
                insCity(1070, "El Dovio", 30);
                insCity(1071, "El Águila", 30);
                insCity(1072, "Florida", 30);
                insCity(1073, "Ginebra", 30);
                insCity(1074, "Guacarí", 30);
                insCity(1075, "Jamundí", 30);
                insCity(1076, "La Cumbre", 30);
                insCity(1077, "La Unión", 30);
                insCity(1078, "La Victoria", 30);
                insCity(1079, "Obando", 30);
                insCity(1080, "Palmira", 30);
                insCity(1081, "Pradera", 30);
                insCity(1082, "Restrepo", 30);
                insCity(1083, "Riofrío", 30);
                insCity(1084, "Roldanillo", 30);
                insCity(1085, "San Pedro", 30);
                insCity(1086, "Sevilla", 30);
                insCity(1087, "Toro", 30);
                insCity(1088, "Trujillo", 30);
                insCity(1089, "Tulúa", 30);
                insCity(1090, "Ulloa", 30);
                insCity(1091, "Versalles", 30);
                insCity(1092, "Vijes", 30);
                insCity(1093, "Yotoco", 30);
                insCity(1094, "Yumbo", 30);
                insCity(1095, "Zarzal", 30);
                insCity(1096, "Carurú", 31);
                insCity(1097, "Mitú", 31);
                insCity(1098, "Taraira", 31);
                insCity(1099, "Cumaribo", 32);
                insCity(1100, "La Primavera", 32);
                insCity(1101, "Puerto Carreño", 32);
                insCity(1102, "Santa Rosalía", 32);
                db.SaveChanges();
            }
        }

        
        public static void insDepto(int id, string nombre)
        {
            var depto = new Departamento
            {
                DepartamentoID = id,
                Nombre = nombre,
            };
            db.Departamentos.Add(depto);
        }
        public static void insCity(int id, string nombre, int iddepto)
        {
            var city = new Ciudad
            {
                CiudadID = id,
                DepartamentoID = iddepto,
                Nombre = nombre,
            };
            db.Ciudades.Add(city);
        }
        public static void insEmpresa()
        {
            var empresaCount = db.Empresas.Count();
            if (empresaCount < 1)
            {
                var empresa = new Empresa
                {
                    Nombre = "MiEmpresa",
                    Telefono = "12345678",
                    Direccion = "Direccion Empresa",
                    DepartamentoID = 21,
                    CiudadID = 801,
                };
                db.Empresas.Add(empresa);
                db.SaveChanges();
            }
        }
        public static void insReceta()
        {
            var recetaCount = db.Recetas.Count();
            if (recetaCount < 1)
            {
                var receta = new Receta
                {
                    RecetaID = 1,
                    Descripcion = "[Terminado]",
                    EmpresaID = 1,
                };
                db.Recetas.Add(receta);
                db.SaveChanges();
            }
        }
        public static void insUnidad(string nombre, int empresa)
        {
            var Unidad = new Unidad
            {
                Descripcion = nombre,
                EmpresaID = empresa,
            };
            db.Unidades.Add(Unidad);
        }

        public void Dispose()
        {
            db.Dispose();
        }
    }
}